name: "Terraform Docs"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_WORKING_DIR: ./terraform

jobs:
  docs:
    name: "Terraform-Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: ${{ env.TF_WORKING_DIR }}
          output-file: TERRAFORM-DOCS.md
          output-method: inject
          git-push: true
# name: Terraform Docs

# on:
#   pull_request:

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         token: ${{ secrets.TERRAFORM_DOCS_PAT_TOKEN }}
#         ref: ${{ github.event.pull_request.head.ref }}
#     - name: Generate TF docs
#       uses: terraform-docs/gh-actions@v1.0.0
#       with:
#         find-dir: /
#         git-push: true
